### ISSUE TITLE
Decouple package from OPA jll?

### ISSUE THREAD

**Issue by tanmaykm** [JuliaComputing/OpenPolicyAgent.jl#15]
It may be good to decouple the package from tight dependency of `OpenPolicyAgent_jll`. The package allows caller to specify an `opa` executable. Not having a tight dependency will allow calling code to avoid installing the jll at all, and not be affected if the jll is not updated/outdated.

**Comment by mortenpi** [comment]
Seems like a good use case for weakdeps maybe?

**Comment by tanmaykm** [comment]
Yes, that is the current thought. We had seen an issue elsewhere (in job image building) when we were using packages with weakdeps in a sysimage... but that's unlikely to affect this package.

**Comment by tanmaykm** [comment]
Actually, weakdeps do not fit the need here. At least not in a simple enough manner. Basically we want to use an `opa` executable in `CLI` module, but without needing `OpenPolicyAgent_jll` to be loaded by default. It seems much simpler to require the executable path to be supplied when creating a new ` CLI.CommandLine` instance. The caller may use `OpenPolicyAgent_jll` or any other source.

**Comment by mortenpi** [comment]
Defaulting to the JLL if available, and, if not,  suggesting to the user to make a conscious decision whether to add it to the environment or point the package to a local binary (with the appropriate version) would be better UX though, no?

Edit: or, actually, automagic stuff for this kind of API is not necessarily good. But in that case it should always be explicitly required? I see the PR defaults to whatever `opa` binary is in the `PATH`.

**Comment by tanmaykm** [comment]
Yeah. I was also in two minds whether to pick up anything by default from the path.
I think I'll change the PR in a bit.
